# ====================================================
# Healthcare Analytics Project
# Module : Data Cleaning
# ====================================================

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../Data/raw/healthcare_dataset.csv")

In [3]:
clean_df = df.copy()

In [4]:
clean_df.shape

(55500, 15)

In [5]:
clean_df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [6]:
missing = clean_df.isnull().sum()

missing_percent = (
    missing / len(clean_df)
) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percent
})

missing_df.sort_values(
    "Percentage",
    ascending=False
)

                    Missing Values  Percentage
Name                             0         0.0
Age                              0         0.0
Gender                           0         0.0
Blood Type                       0         0.0
Medical Condition                0         0.0
Date of Admission                0         0.0
Doctor                           0         0.0
Hospital                         0         0.0
Insurance Provider               0         0.0
Billing Amount                   0         0.0
Room Number                      0         0.0
Admission Type                   0         0.0
Discharge Date                   0         0.0
Medication                       0         0.0
Test Results                     0         0.0

In [7]:
clean_df = clean_df.drop_duplicates()

In [8]:
clean_df.dtypes

Name                      str
Age                     int64
Gender                    str
Blood Type                str
Medical Condition         str
Date of Admission         str
Doctor                    str
Hospital                  str
Insurance Provider        str
Billing Amount        float64
Room Number             int64
Admission Type            str
Discharge Date            str
Medication                str
Test Results              str
dtype: object

In [9]:
clean_df["Date of Admission"] = pd.to_datetime(
    clean_df["Date of Admission"]
)

clean_df["Discharge Date"] = pd.to_datetime(
    clean_df["Discharge Date"]
)

In [10]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  str
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  str
 3   Blood Type          54966 non-null  str
 4   Medical Condition   54966 non-null  str
 5   Date of Admission   54966 non-null  datetime64[us]
 6   Doctor              54966 non-null  str
 7   Hospital            54966 non-null  str
 8   Insurance Provider  54966 non-null  str
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  str
 12  Discharge Date      54966 non-null  datetime64[us]
 13  Medication          54966 non-null  str
 14  Test Results        54966 non-null  str
dtypes: datetime64[us](2), float64(1), int64(2), str(10)
memory usage: 11.6 MB

In [11]:
clean_df.describe()

,Age,Date of Admission,Billing Amount,Room Number,Discharge Date
count,54966.000000,54966,54966.000000,54966.000000,54966
mean,51.535185,2021-11-01 17:35:29.505512,25544.306284,301.124404,2021-11-17 05:34:28.202161
min,13.000000,2019-05-08 00:00:00,-2008.492140,101.000000,2019-05-09 00:00:00
25%,35.000000,2020-07-28 00:00:00,13243.718641,202.000000,2020-08-13 00:00:00
50%,52.000000,2021-11-02 00:00:00,25542.749145,302.000000,2021-11-18 00:00:00
75%,68.000000,2023-02-03 00:00:00,37819.858159,401.000000,2023-02-19 00:00:00
max,89.000000,2024-05-07 00:00:00,52764.276736,500.000000,2024-06-06 00:00:00
std,19.605661,NaN,14208.409711,115.223143,NaN

In [12]:
clean_df.describe(include="object")

C:\Users\pnaik\AppData\Local\Temp\ipykernel_10320\2423925770.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  clean_df.describe(include="object")

,Name,Gender,Blood Type,Medical Condition,Doctor,Hospital,Insurance Provider,Admission Type,Medication,Test Results
count,54966,54966,54966,54966,54966,54966,54966,54966,54966,54966
unique,49992,2,8,6,40341,39876,5,3,5,3
top,DAvId muNoZ,Male,A-,Arthritis,Michael Smith,LLC Smith,Cigna,Elective,Lipitor,Abnormal
freq,3,27496,6898,9218,27,44,11139,18473,11038,18437

In [13]:
clean_df.to_csv(
    "../Data/cleaned/healthcare_cleaned.csv",
    index=False
)

In [14]:
print("Healthcare dataset cleaned successfully.")

Healthcare dataset cleaned successfully.

In [15]:
clean_df["Date of Admission"] = pd.to_datetime(clean_df["Date of Admission"])
clean_df["Discharge Date"] = pd.to_datetime(clean_df["Discharge Date"])

clean_df.info()

<class 'pandas.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  str
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  str
 3   Blood Type          54966 non-null  str
 4   Medical Condition   54966 non-null  str
 5   Date of Admission   54966 non-null  datetime64[us]
 6   Doctor              54966 non-null  str
 7   Hospital            54966 non-null  str
 8   Insurance Provider  54966 non-null  str
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  str
 12  Discharge Date      54966 non-null  datetime64[us]
 13  Medication          54966 non-null  str
 14  Test Results        54966 non-null  str
dtypes: datetime64[us](2), float64(1), int64(2), str(10)
memory usage: 11.6 MB