# Healthcare Analytics Project

# Module: Feature Engineering

## Objective

Create new business-friendly columns for better analysis in SQL and Power BI.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
df = pd.read_csv("../Data/cleaned/healthcare_cleaned.csv")

In [3]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

In [4]:
df["Length of Stay"] = (
    df["Discharge Date"] -
    df["Date of Admission"]
).dt.days

In [5]:
df[["Date of Admission","Discharge Date","Length of Stay"]].head()

  Date of Admission Discharge Date  Length of Stay
0        2024-01-31     2024-02-02               2
1        2019-08-20     2019-08-26               6
2        2022-09-22     2022-10-07              15
3        2020-11-18     2020-12-18              30
4        2022-09-19     2022-10-09              20

In [6]:
df["Age Group"] = pd.cut(
    df["Age"],
    bins=[0,18,35,50,65,100],
    labels=[
        "Child",
        "Young Adult",
        "Adult",
        "Senior Adult",
        "Elderly"
    ]
)

In [7]:
df["Age Group"].value_counts()

Age Group
Elderly         16096
Young Adult     13519
Senior Adult    12298
Adult           12167
Child             886
Name: count, dtype: int64

In [8]:
df["Admission Year"] = df["Date of Admission"].dt.year

In [9]:
df["Admission Month"] = df["Date of Admission"].dt.month_name()

In [10]:
df["Admission Day"] = df["Date of Admission"].dt.day_name()

In [11]:
df["Billing Category"] = pd.qcut(
    df["Billing Amount"],
    q=3,
    labels=[
        "Low",
        "Medium",
        "High"
    ]
)

In [12]:
df["Billing Category"].value_counts()

Billing Category
Medium    18323
Low       18322
High      18321
Name: count, dtype: int64

In [13]:
df.to_csv(
    "../Data/cleaned/healthcare_feature_engineered.csv",
    index=False
)

In [14]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group,Admission Year,Admission Month,Admission Day,Billing Category
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,Young Adult,2024,January,Wednesday,Medium
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Senior Adult,2019,August,Tuesday,Medium
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,Elderly,2022,September,Thursday,Medium
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Young Adult,2020,November,Wednesday,High
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Adult,2022,September,Monday,Low